import { useEffect, useState } from "react";
import type { LongFormEndingPlan, LongFormMechanicsPlan, LongFormRoutePlan } from "../../api/long-form.js";
const lines = (value: string) => value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean);
const id = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
const replace = <T,>(items: T[], index: number, value: T) => items.map((item, i) => i === index ? value : item);

export function MechanicsEditor(props: {
  plan: LongFormMechanicsPlan; routes: LongFormRoutePlan | null; endings: LongFormEndingPlan | null;
  busy: boolean; onSave(plan: LongFormMechanicsPlan): Promise<void>;
}) {
  const [draft, setDraft] = useState(props.plan); useEffect(() => setDraft(props.plan), [props.plan]);
  const mechanics = [...draft.visibleStats, ...draft.relationships, ...draft.flags, ...draft.resources];
  const used = new Set([...draft.gates.flatMap((g) => g.conditions.map((c) => c.mechanicKey)), ...draft.choiceEffectPlans.flatMap((e) => e.mechanicKeys)]);
  const unused = mechanics.filter((item) => !used.has(item.key));
  return <form className="brief-editor mechanics-editor" onSubmit={(event) => { event.preventDefault(); void props.onSave(draft); }}>
    <section className="brief-section"><h3>Consequence model</h3>
      <label>Title<input required value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} /></label>
      <label>Overview<textarea value={draft.overview} onChange={(e) => setDraft({ ...draft, overview: e.target.value })} /></label>
      <div className="route-budget">
        <Metric label="Declared" value={mechanics.length} /><Metric label="Influential" value={mechanics.length - unused.length} />
        <Metric label="Gates" value={draft.gates.length} /><Metric label="Effect plans" value={draft.choiceEffectPlans.length} />
      </div>
      {unused.length > 0 && <p className="warning">Not yet influential: {unused.map((item) => item.label).join(", ")}. Add each to a gate or choice-effect plan before approval.</p>}
    </section>
    <ScaleSection title="Visible stats" values={draft.visibleStats} onChange={(visibleStats) => setDraft({ ...draft, visibleStats })} />
    <ScaleSection title="Relationship scales" values={draft.relationships} onChange={(relationships) => setDraft({ ...draft, relationships })} relationships />
    <section className="brief-section"><Section title="Flags and resources" onAdd={() => setDraft({ ...draft, flags: [...draft.flags, { id: id("flag"), key: `flag_${draft.flags.length + 1}`, label: "New flag", meaning: "" }] })} />
      {draft.flags.map((flag, index) => <KeyCard key={flag.id} label={flag.label} keyValue={flag.key} meaning={flag.meaning}
        onChange={(key, label, meaning) => setDraft({ ...draft, flags: replace(draft.flags, index, { ...flag, key, label, meaning }) })} />)}
      <button type="button" onClick={() => setDraft({ ...draft, resources: [...draft.resources, { id: id("resource"), key: `resource_${draft.resources.length + 1}`, label: "New resource", kind: "counter", initial: 0, meaning: "" }] })}>Add resource</button>
      {draft.resources.map((resource, index) => <details className="bible-card route-detail-card" key={resource.id}><summary>{resource.label} · {resource.kind}</summary>
        <KeyCard label={resource.label} keyValue={resource.key} meaning={resource.meaning} onChange={(key, label, meaning) => setDraft({ ...draft, resources: replace(draft.resources, index, { ...resource, key, label, meaning }) })} />
        <div className="brief-grid"><label>Kind<select value={resource.kind} onChange={(e) => setDraft({ ...draft, resources: replace(draft.resources, index, { ...resource, kind: e.target.value as typeof resource.kind }) })}><option value="inventory">Inventory</option><option value="currency">Currency</option><option value="counter">Counter</option></select></label>
        <label>Initial<input type="number" value={resource.initial} onChange={(e) => setDraft({ ...draft, resources: replace(draft.resources, index, { ...resource, initial: Number(e.target.value) }) })} /></label></div>
      </details>)}
    </section>
    <section className="brief-section"><Section title="Route and ending gates" onAdd={() => {
      const first = mechanics[0]; const target = props.endings?.endings[0]; if (!first || !target) return;
      setDraft({ ...draft, gates: [...draft.gates, { id: id("gate"), targetType: "ending", targetId: target.id, logic: "all", conditions: [{ id: id("condition"), mechanicKey: first.key, operator: "at-least", value: 1 }], rationale: "", fallback: "" }] });
    }} />
      {draft.gates.map((gate, index) => <details className="bible-card route-detail-card" key={gate.id}><summary>{gate.targetType} · {gate.targetId} · {gate.conditions.length} condition(s)</summary>
        <div className="brief-grid"><label>Target type<select value={gate.targetType} onChange={(e) => setDraft({ ...draft, gates: replace(draft.gates, index, { ...gate, targetType: e.target.value as typeof gate.targetType }) })}><option value="route">Route</option><option value="ending">Ending</option></select></label>
        <label>Target<select value={gate.targetId} onChange={(e) => setDraft({ ...draft, gates: replace(draft.gates, index, { ...gate, targetId: e.target.value }) })}>{(gate.targetType === "route" ? props.routes?.routes : props.endings?.endings)?.map((item) => <option key={item.id} value={item.id}>{"name" in item ? item.name : item.title}</option>)}</select></label></div>
        {gate.conditions.map((condition, ci) => <div className="mechanic-condition" key={condition.id}><select value={condition.mechanicKey} onChange={(e) => setDraft({ ...draft, gates: replace(draft.gates, index, { ...gate, conditions: replace(gate.conditions, ci, { ...condition, mechanicKey: e.target.value }) }) })}>{mechanics.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select><select value={condition.operator} onChange={(e) => setDraft({ ...draft, gates: replace(draft.gates, index, { ...gate, conditions: replace(gate.conditions, ci, { ...condition, operator: e.target.value as typeof condition.operator }) }) })}>{["at-least","at-most","equals","present","absent"].map((value) => <option key={value}>{value}</option>)}</select><input type="number" value={condition.value ?? 0} onChange={(e) => setDraft({ ...draft, gates: replace(draft.gates, index, { ...gate, conditions: replace(gate.conditions, ci, { ...condition, value: Number(e.target.value) }) }) })} /></div>)}
        <label>Rationale<textarea value={gate.rationale} onChange={(e) => setDraft({ ...draft, gates: replace(draft.gates, index, { ...gate, rationale: e.target.value }) })} /></label><label>Fallback content<textarea value={gate.fallback} onChange={(e) => setDraft({ ...draft, gates: replace(draft.gates, index, { ...gate, fallback: e.target.value }) })} /></label>
      </details>)}
    </section>
    <section className="brief-section"><Section title="Choice-effect plans" onAdd={() => { const first = mechanics[0]; if (first) setDraft({ ...draft, choiceEffectPlans: [...draft.choiceEffectPlans, { id: id("effect"), label: "New effect plan", sourceDecisionIds: [], mechanicKeys: [first.key], effectGuidance: ["Describe when and why this value changes."] }] }); }} />
      {draft.choiceEffectPlans.map((effect, index) => <details className="bible-card route-detail-card" key={effect.id}><summary>{effect.label} · {effect.mechanicKeys.join(", ")}</summary><label>Label<input value={effect.label} onChange={(e) => setDraft({ ...draft, choiceEffectPlans: replace(draft.choiceEffectPlans, index, { ...effect, label: e.target.value }) })} /></label><Lines label="Decision IDs" values={effect.sourceDecisionIds} onChange={(sourceDecisionIds) => setDraft({ ...draft, choiceEffectPlans: replace(draft.choiceEffectPlans, index, { ...effect, sourceDecisionIds }) })} /><Lines label="Mechanic keys" values={effect.mechanicKeys} onChange={(mechanicKeys) => setDraft({ ...draft, choiceEffectPlans: replace(draft.choiceEffectPlans, index, { ...effect, mechanicKeys }) })} /><Lines label="Effect guidance" values={effect.effectGuidance} onChange={(effectGuidance) => setDraft({ ...draft, choiceEffectPlans: replace(draft.choiceEffectPlans, index, { ...effect, effectGuidance }) })} /></details>)}
    </section>
    <section className="brief-section"><Section title="Balancing rules" onAdd={() => setDraft({ ...draft, balancingRules: [...draft.balancingRules, { id: id("rule"), label: "New rule", description: "" }] })} />{draft.balancingRules.map((rule, index) => <KeyCard key={rule.id} label={rule.label} keyValue={rule.id} meaning={rule.description} hideKey onChange={(_, label, description) => setDraft({ ...draft, balancingRules: replace(draft.balancingRules, index, { ...rule, label, description }) })} />)}</section>
    <div className="brief-actions"><button className="primary" disabled={props.busy}>{props.busy ? "Saving…" : "Save mechanics draft"}</button></div>
  </form>;
}

function ScaleSection(props: { title: string; values: LongFormMechanicsPlan["visibleStats"] | LongFormMechanicsPlan["relationships"]; onChange(values: any): void; relationships?: boolean }) {
  return <section className="brief-section"><Section title={props.title} onAdd={() => props.onChange([...props.values, { id: id("scale"), ...(props.relationships ? { relationshipId: "relationship-id", bands: [] } : {}), key: `scale_${props.values.length + 1}`, label: "New scale", description: "", minimum: -5, maximum: 10, initial: 0, increaseSignals: [], decreaseSignals: [] }])} />{props.values.map((value, index) => <details className="bible-card route-detail-card" key={value.id}><summary>{value.label} · {value.key} · {value.minimum}…{value.maximum}</summary><div className="brief-grid"><label>Label<input value={value.label} onChange={(e) => props.onChange(replace(props.values as any[], index, { ...value, label: e.target.value }))} /></label><label>Key<input value={value.key} onChange={(e) => props.onChange(replace(props.values as any[], index, { ...value, key: e.target.value }))} /></label><label>Minimum<input type="number" value={value.minimum} onChange={(e) => props.onChange(replace(props.values as any[], index, { ...value, minimum: Number(e.target.value) }))} /></label><label>Maximum<input type="number" value={value.maximum} onChange={(e) => props.onChange(replace(props.values as any[], index, { ...value, maximum: Number(e.target.value) }))} /></label><label>Initial<input type="number" value={value.initial} onChange={(e) => props.onChange(replace(props.values as any[], index, { ...value, initial: Number(e.target.value) }))} /></label></div><label>Description<textarea value={value.description} onChange={(e) => props.onChange(replace(props.values as any[], index, { ...value, description: e.target.value }))} /></label><Lines label="Increase signals" values={value.increaseSignals} onChange={(increaseSignals) => props.onChange(replace(props.values as any[], index, { ...value, increaseSignals }))} /><Lines label="Decrease signals" values={value.decreaseSignals} onChange={(decreaseSignals) => props.onChange(replace(props.values as any[], index, { ...value, decreaseSignals }))} /></details>)}</section>;
}
function KeyCard(props: { label: string; keyValue: string; meaning: string; hideKey?: boolean; onChange(key: string, label: string, meaning: string): void }) { return <article className="bible-card"><div className="brief-grid"><label>Label<input value={props.label} onChange={(e) => props.onChange(props.keyValue, e.target.value, props.meaning)} /></label>{!props.hideKey && <label>Key<input value={props.keyValue} onChange={(e) => props.onChange(e.target.value, props.label, props.meaning)} /></label>}</div><label>Description<textarea value={props.meaning} onChange={(e) => props.onChange(props.keyValue, props.label, e.target.value)} /></label></article>; }
function Lines(props: { label: string; values: string[]; onChange(values: string[]): void }) { return <label>{props.label}<textarea value={props.values.join("\n")} onChange={(e) => props.onChange(lines(e.target.value))} /></label>; }
function Section(props: { title: string; onAdd(): void }) { return <header className="bible-section-heading"><h3>{props.title}</h3><button type="button" onClick={props.onAdd}>Add</button></header>; }
function Metric(props: { label: string; value: number }) { return <div><strong>{props.value}</strong><span>{props.label}</span></div>; }
